language: node_js
node_js:
- 10.11.0
before_install:
- cd ./quiz-backend
deploy:
  provider: heroku
  skip_cleanup: true
  script: echo "npm test temporarily disabled"
  api_key:
    secure: EFjni/Lz9CUwF8Sr87YEXu3Oe4oen21QPQlNjgfsu4tj7FJVso2Z2sieS+0f8l8FHlZeHkacuewHoBqXEHJl9JSMHHLiVLTNAGqtRKQfaneD2Qa2mBcofUuR9y+E031N2/gBvBM/mliY82kZMX4inJSlnhCYXpYR4wtzlnsSsax1z0DslJBXJ7C0fQW1Vz46p5wI8LmGFDp4S96wyvrCkfJRt1ghz1PY4R1oqmuup1RcCVuz0Fl6p+2c6WdpnnGQRwm52ax86ZVKIbl7nyEv39RyV1pOjnm1SqLBI92HJ4DxCS2MZc0r+W3z3YAAXgjQHlFVZ2BNzbGFmnbEIad73A0SkEwiyL2gJBrv5M03UhTv8zCzOB7b/oB8cSqBprKp6aYbmpvWYTfJ8XqQwMty30M+5awUPDcKsDk+LdK7WXjdvirru0N+PoYp8WWb6BN94kUid0/iS54hNgC1OsGr/OCxdIuim1xPTT8C5IZgAMrTDCe+dqucms51euutM9S+SwsOAsQdhhsIppb165t32o4d6pNklGcTdbNtvHlpKDlEmCs8vzqr42DE8CzC0fhOa5wl3hYnZfKZSszxxVqbqc3t4SJl1CuN+sQg1dwCE8KdWiSfRP0McO3BfVUNqLmflWnA7LWsDKdEH3h7bchbH/r6hSohAn5+TMqA/7fNY7E=
  app: tietovisa
  on:
    repo: MinnaVares/Quiz
    branch: master
